import type { Format } from "../types";
import { generate } from "./generate";
import { load } from "./load";

/**
 * `model-json` — format-neutral serialised Model. Canonical shape on
 * emit: `{ schemaVersion: 1, model: Model }`. Load accepts that plus
 * two compat shapes (CliEnvelope<ModelData> from `aact model --json`,
 * and raw Model for hand-authored snapshots).
 *
 * Capabilities: load + generate, **no fix** — JSON does not have a
 * meaningful "source range" semantics for C4 edits; range-based
 * --fix has nothing to anchor on. For authoring use PUML / DSL;
 * model-json is the LLM-input / snapshot / cross-tool surface.
 *
 * Canonical extension: `*.aact.json`. The defaultPattern is strict
 * (not `*.json`) on purpose — explicit-over-guess given the
 * proliferation of unrelated JSON in any real project (package.json,
 * SARIF output, Structurizr workspace.json). Files like `my-arch.json`
 * require `source.type: "model-json"` in `aact.config.ts` or
 * `--baseline-format model-json` for `aact diff`.
 *
 * LSP note: a workspace sourced from model-json carries no original
 * `sourceLocation`s unless the JSON was generated by aact itself.
 * `aact check` violations on a hand-authored JSON anchor file-level
 * only; this is acceptable — model-json is not an authoring source.
 */
export const modelJsonFormat: Format = {
  name: "model-json",
  defaultPattern: "*.aact.json",
  load,
  generate,
};
