import YAML from "yaml";

import { generate } from "../../../src/formats/compose/generate";
import type { Model } from "../../../src/model";
import type { ElementSpec } from "../../helpers/makeModel";
import { makeModel } from "../../helpers/makeModel";

/**
 * Compose generator tests.
 *
 * Покрывают три класса behaviour'ов:
 *  1. Classification — кто попадает в `services:`, в `models:`, и
 *     кого мы выбрасываем (Person / external non-AI System).
 *  2. Image inference — technology → image, default образа для
 *     ContainerDb / ContainerQueue, build-only сервисы.
 *  3. Round-trip — `load(generate(M))` для core полей даёт Model
 *     эквивалентную исходной (имена, kinds, depends_on, AI models).
 *
 * Тесты избегают snapshot'ов поверх raw YAML строки — parse'ят
 * output через `YAML.parse` и проверяют семантику. Это устойчиво к
 * cosmetic'у формата (whitespace / quote style) и держит focus на
 * round-trip contract'е, а не текстовом выводе.
 */

const buildOutput = (elements: ElementSpec[], workspace?: { name: string }) => {
  const partial = workspace ? { workspace } : {};
  const model: Model = { ...makeModel({ elements }), ...partial };
  const output = generate(model);
  expect(output.files).toHaveLength(1);
  expect(output.files[0].path).toBe("compose.yml");
  return {
    raw: output.files[0].content,
    parsed: YAML.parse(output.files[0].content) as Record<string, unknown>,
  };
};

describe("compose generate — classification", () => {
  it("emits header even for empty model", () => {
    const output = generate(makeModel({}));
    expect(output.files).toHaveLength(1);
    expect(output.files[0].path).toBe("compose.yml");
    expect(output.files[0].content).toContain("Generated by aact");
    // Empty model => no services / models / name keys
    expect(YAML.parse(output.files[0].content)).toBeNull();
  });

  it("includes only non-Person internal Elements as services", () => {
    const { parsed } = buildOutput([
      { name: "api" },
      { name: "ops", kind: "Person" },
      { name: "stripe", kind: "System", external: true },
    ]);
    const services = parsed.services as Record<string, unknown>;
    expect(Object.keys(services)).toEqual(["api"]);
  });

  it("emits AI-model Elements into top-level models block", () => {
    const { parsed } = buildOutput([
      {
        name: "api",
        relations: [{ to: "llama3" }],
      },
      {
        name: "llama3",
        kind: "System",
        external: true,
        technology: "AI model",
        description: "ai/llama3.2",
      },
    ]);
    const models = parsed.models as Record<string, { model: string }>;
    expect(models).toEqual({ llama3: { model: "ai/llama3.2" } });
    const services = parsed.services as Record<
      string,
      { models?: readonly string[] }
    >;
    expect(services.api.models).toEqual(["llama3"]);
  });

  it("emits workspace.name as top-level compose name", () => {
    const { parsed } = buildOutput([{ name: "api" }], { name: "shop-app" });
    expect(parsed.name).toBe("shop-app");
  });

  it("sorts services alphabetically (deterministic output)", () => {
    const { raw } = buildOutput([
      { name: "zeta" },
      { name: "alpha" },
      { name: "mu" },
    ]);
    const order = ["alpha:", "mu:", "zeta:"].map((k) => raw.indexOf(k));
    expect(order).toEqual([...order].toSorted((a, b) => a - b));
  });

  it("produces byte-identical output across runs (determinism)", () => {
    const model = makeModel({
      elements: [
        { name: "api", relations: [{ to: "db" }] },
        { name: "db", kind: "ContainerDb" },
      ],
    });
    expect(generate(model).files[0].content).toBe(
      generate(model).files[0].content,
    );
  });
});

describe("compose generate — image inference", () => {
  it("uses technology as image when it looks like a ref", () => {
    const { parsed } = buildOutput([
      { name: "api", technology: "node:20-alpine" },
    ]);
    const svc = (parsed.services as Record<string, { image: string }>).api;
    expect(svc.image).toBe("node:20-alpine");
  });

  it("lowercases technology image ref", () => {
    const { parsed } = buildOutput([{ name: "api", technology: "Node:20" }]);
    expect(
      (parsed.services as Record<string, { image: string }>).api.image,
    ).toBe("node:20");
  });

  it("omits image for Container without parseable technology", () => {
    const { parsed } = buildOutput([{ name: "api", technology: "Next.js 14" }]);
    const svc = (parsed.services as Record<string, { image?: string }>).api;
    expect(svc.image).toBeUndefined();
  });

  it("defaults ContainerDb to postgres:latest when technology absent", () => {
    const { parsed } = buildOutput([{ name: "db", kind: "ContainerDb" }]);
    expect(
      (parsed.services as Record<string, { image: string }>).db.image,
    ).toBe("postgres:latest");
  });

  it("defaults ContainerQueue to rabbitmq:latest when technology absent", () => {
    const { parsed } = buildOutput([{ name: "bus", kind: "ContainerQueue" }]);
    expect(
      (parsed.services as Record<string, { image: string }>).bus.image,
    ).toBe("rabbitmq:latest");
  });

  it("preserves registry-prefixed image refs", () => {
    const { parsed } = buildOutput([
      { name: "api", technology: "ghcr.io/org/api:v1.2" },
    ]);
    expect(
      (parsed.services as Record<string, { image: string }>).api.image,
    ).toBe("ghcr.io/org/api:v1.2");
  });
});

describe("compose generate — relations", () => {
  it("emits depends_on for internal relations only", () => {
    const { parsed } = buildOutput([
      {
        name: "api",
        relations: [{ to: "db" }, { to: "stripe" }, { to: "alice" }],
      },
      { name: "db", kind: "ContainerDb" },
      { name: "stripe", kind: "System", external: true },
      { name: "alice", kind: "Person" },
    ]);
    const api = (parsed.services as Record<string, { depends_on: string[] }>)
      .api;
    expect(api.depends_on).toEqual(["db"]);
  });

  it("sorts depends_on alphabetically", () => {
    const { parsed } = buildOutput([
      {
        name: "api",
        relations: [{ to: "z" }, { to: "a" }, { to: "m" }],
      },
      { name: "z" },
      { name: "a" },
      { name: "m" },
    ]);
    expect(
      (parsed.services as Record<string, { depends_on: string[] }>).api
        .depends_on,
    ).toEqual(["a", "m", "z"]);
  });

  it("omits depends_on when no relations", () => {
    const { parsed } = buildOutput([{ name: "api" }]);
    const api = (parsed.services as Record<string, { depends_on?: unknown }>)
      .api;
    expect(api.depends_on).toBeUndefined();
  });
});

describe("compose generate — labels (round-trip metadata)", () => {
  it("emits aact.description when present", () => {
    const { parsed } = buildOutput([
      { name: "api", description: "Public REST API" },
    ]);
    const api = (
      parsed.services as Record<string, { labels: Record<string, string> }>
    ).api;
    expect(api.labels["aact.description"]).toBe("Public REST API");
  });

  it("joins tags with commas in aact.tags", () => {
    const { parsed } = buildOutput([
      { name: "api", tags: ["public", "tier-1"] },
    ]);
    const api = (
      parsed.services as Record<string, { labels: Record<string, string> }>
    ).api;
    expect(api.labels["aact.tags"]).toBe("public,tier-1");
  });

  it("emits aact.link when set", () => {
    const { parsed } = buildOutput([
      { name: "api", link: "https://docs.example.com/api" },
    ]);
    expect(
      (parsed.services as Record<string, { labels: Record<string, string> }>)
        .api.labels["aact.link"],
    ).toBe("https://docs.example.com/api");
  });

  it("emits aact.label only when label diverges from humanize(name)", () => {
    // Loader compose canonicalizes label через `humanize(name)`. Тест
    // эмитит две модели — одну с canonical label (round-trip stable),
    // другую с custom label (требует aact.label чтобы сохранить).
    const { parsed } = buildOutput([
      { name: "api-gateway", label: "Api Gateway" }, // canonical
      { name: "auth-svc", label: "Authentication" }, // custom
    ]);
    const services = parsed.services as Record<
      string,
      { labels?: Record<string, string> }
    >;
    expect(services["api-gateway"].labels?.["aact.label"]).toBeUndefined();
    expect(services["auth-svc"].labels?.["aact.label"]).toBe("Authentication");
  });

  it("emits aact.kind for Component-family kinds", () => {
    const { parsed } = buildOutput([
      { name: "auth", kind: "Component" },
      { name: "auth-db", kind: "ComponentDb" },
    ]);
    const services = parsed.services as Record<
      string,
      { labels: Record<string, string> }
    >;
    expect(services.auth.labels["aact.kind"]).toBe("Component");
    expect(services["auth-db"].labels["aact.kind"]).toBe("ComponentDb");
  });

  it("skips aact.kind for ContainerDb when technology hints DB engine", () => {
    const { parsed } = buildOutput([
      { name: "db", kind: "ContainerDb", technology: "postgres:16" },
    ]);
    const db = (
      parsed.services as Record<string, { labels?: Record<string, string> }>
    ).db;
    expect(db.labels?.["aact.kind"]).toBeUndefined();
  });

  it("emits aact.kind for ContainerDb when technology is non-suggestive", () => {
    const { parsed } = buildOutput([
      { name: "db", kind: "ContainerDb", technology: "custom-store:1" },
    ]);
    expect(
      (parsed.services as Record<string, { labels: Record<string, string> }>).db
        .labels["aact.kind"],
    ).toBe("ContainerDb");
  });

  it("respects custom label prefix via options", () => {
    const model = makeModel({
      elements: [{ name: "api", description: "Public API" }],
    });
    const output = generate(model, { labels: { prefix: "arch" } });
    const parsed = YAML.parse(output.files[0].content) as {
      services: Record<string, { labels: Record<string, string> }>;
    };
    expect(parsed.services.api.labels["arch.description"]).toBe("Public API");
    expect(parsed.services.api.labels["aact.description"]).toBeUndefined();
  });
});

describe("compose generate — round-trip via loader", () => {
  it("load(generate(M)) preserves services, kinds, and depends_on", async () => {
    const { composeFormat } = await import("../../../src/formats/compose");

    const model: Model = {
      ...makeModel({
        elements: [
          {
            name: "api",
            description: "Public REST API",
            technology: "node:20",
            relations: [{ to: "db" }, { to: "cache" }],
          },
          {
            name: "db",
            kind: "ContainerDb",
            technology: "postgres:16",
          },
          {
            name: "cache",
            kind: "ContainerDb",
            technology: "redis:7",
          },
        ],
      }),
      workspace: { name: "demo-app" },
    };

    const generated = generate(model);
    expect(generated.files).toHaveLength(1);

    // Round-trip через physical FS — loader читает с диска.
    const { mkdtemp, writeFile } = await import("node:fs/promises");
    const { tmpdir } = await import("node:os");
    // eslint-disable-next-line @typescript-eslint/unbound-method
    const { join } = await import("node:path");
    const dir = await mkdtemp(join(tmpdir(), "aact-compose-rt-"));
    const composePath = join(dir, "compose.yml");
    await writeFile(composePath, generated.files[0].content, "utf8");

    if (!composeFormat.load) throw new Error("compose has no load");
    const { model: loaded, issues } = await composeFormat.load(composePath);

    expect(issues.filter((i) => i.kind !== "loader-warning")).toEqual([]);
    expect(Object.keys(loaded.elements).toSorted()).toEqual([
      "api",
      "cache",
      "db",
    ]);
    expect(loaded.elements.api.kind).toBe("Container");
    expect(loaded.elements.db.kind).toBe("ContainerDb");
    expect(loaded.elements.cache.kind).toBe("ContainerDb");
    expect(loaded.elements.api.description).toBe("Public REST API");
    expect(loaded.elements.api.relations.map((r) => r.to).toSorted()).toEqual([
      "cache",
      "db",
    ]);
    expect(loaded.workspace?.name).toBe("demo-app");
  });

  it("round-trip preserves AI-model declarations and references", async () => {
    const { composeFormat } = await import("../../../src/formats/compose");
    const model: Model = makeModel({
      elements: [
        {
          name: "api",
          relations: [{ to: "llama3" }],
        },
        {
          name: "llama3",
          kind: "System",
          external: true,
          technology: "AI model",
          description: "ai/llama3.2",
        },
      ],
    });

    const generated = generate(model);
    const { mkdtemp, writeFile } = await import("node:fs/promises");
    const { tmpdir } = await import("node:os");
    // eslint-disable-next-line @typescript-eslint/unbound-method
    const { join } = await import("node:path");
    const dir = await mkdtemp(join(tmpdir(), "aact-compose-rt-ai-"));
    const composePath = join(dir, "compose.yml");
    await writeFile(composePath, generated.files[0].content, "utf8");

    if (!composeFormat.load) throw new Error("compose has no load");
    const { model: loaded } = await composeFormat.load(composePath);

    expect(loaded.elements.llama3?.external).toBe(true);
    expect(loaded.elements.llama3?.technology).toBe("AI model");
    expect(loaded.elements.llama3?.description).toBe("ai/llama3.2");
    expect(loaded.elements.api?.relations.map((r) => r.to)).toContain("llama3");
  });
});
