import YAML from "yaml";

import type { Element, Model } from "../../model";
import type { FormatOutput } from "../types";

/**
 * Compose generator: Model → `compose.yml` (single file).
 *
 * Симметрично loader'у:
 *  - Каждый internal не-Person Element → entry в `services:`
 *  - Каждый external Element с `technology === "AI model"` → entry
 *    в top-level `models:` (Compose Spec 2026)
 *  - Workspace name → top-level `name:`
 *  - Persons / Boundaries / external non-AI Elements — skip
 *    (compose не имеет аналогов; user добавляет руками если нужно)
 *
 * Labels конвенции зеркальны loader'у (default prefix `aact`,
 * пользователь меняет через `ComposeGenerateOptions.labels.prefix`):
 *  - `aact.kind`        — kind override если не выводится из image
 *  - `aact.label`       — non-canonical human label
 *  - `aact.description` — description (compose не имеет native поля)
 *  - `aact.tags`        — comma-separated tags
 *  - `aact.link`        — external link / doc ref
 *
 * External Elements (kind="System", external=true) в `services:`
 * не эмитятся; внешние AI-модели идут в top-level `models:` блок —
 * остальные external Systems считаются "не часть нашего compose"
 * (provider services без типа сгенерить нельзя из Model'а).
 *
 * Round-trip контракт: `load(generate(M))` дает Model эквивалентную
 * `M` для всех C4-meaningful полей. Compose-specific runtime поля
 * (volumes / networks / resources / etc) генератор не пишет — это
 * runtime concerns, не architecture.
 *
 * Output детерминирован (services отсортированы по имени), чтобы
 * diff against existing compose.yml был стабильным.
 */

export interface ComposeGenerateOptions {
  readonly labels?: {
    /** Default `"aact"`. Меняется только если в проекте занят prefix. */
    readonly prefix?: string;
  };
}

export const generate = (model: Model, options?: unknown): FormatOutput => {
  const opts = (options as ComposeGenerateOptions | undefined) ?? {};
  const prefix = opts.labels?.prefix ?? "aact";

  const services = collectInternalElements(model);
  const models = collectAiModels(model);

  const doc: Record<string, unknown> = {};
  if (model.workspace?.name) {
    doc.name = model.workspace.name;
  }
  if (services.length > 0) {
    doc.services = buildServicesBlock(services, model, prefix);
  }
  if (models.length > 0) {
    doc.models = buildModelsBlock(models);
  }

  const body =
    Object.keys(doc).length === 0
      ? ""
      : YAML.stringify(doc, {
          indent: 2,
          lineWidth: 0,
          singleQuote: false,
        });

  const header =
    "# Generated by aact — Docker Compose Spec 2026\n" +
    "# Round-trip: load this file back via `aact view` / `aact diff`\n";

  return {
    files: [
      {
        path: "compose.yml",
        content: body.length > 0 ? `${header}\n${body}` : header,
      },
    ],
  };
};

/* ------------------------------------------------------------------ */
/*  Element classification                                            */
/* ------------------------------------------------------------------ */

const collectInternalElements = (model: Model): readonly Element[] =>
  Object.values(model.elements)
    .filter((el) => !el.external && el.kind !== "Person")
    .toSorted((a, b) => a.name.localeCompare(b.name));

const isAiModelElement = (el: Element): boolean =>
  el.external &&
  el.kind === "System" &&
  el.technology?.toLowerCase() === "ai model";

const collectAiModels = (model: Model): readonly Element[] =>
  Object.values(model.elements)
    .filter(isAiModelElement)
    .toSorted((a, b) => a.name.localeCompare(b.name));

/* ------------------------------------------------------------------ */
/*  Services emission                                                 */
/* ------------------------------------------------------------------ */

const buildServicesBlock = (
  services: readonly Element[],
  model: Model,
  prefix: string,
): Record<string, Record<string, unknown>> => {
  const out: Record<string, Record<string, unknown>> = {};
  for (const el of services) {
    out[el.name] = buildService(el, model, prefix);
  }
  return out;
};

const buildService = (
  el: Element,
  model: Model,
  prefix: string,
): Record<string, unknown> => {
  const service: Record<string, unknown> = {};

  const image = inferImage(el);
  if (image !== undefined) {
    service.image = image;
  }

  const dependsOn = collectDependsOn(el, model);
  if (dependsOn.length > 0) {
    service.depends_on = [...dependsOn];
  }

  const aiModels = collectAiModelRefs(el, model);
  if (aiModels.length > 0) {
    service.models = [...aiModels];
  }

  const labels = buildLabels(el, prefix);
  if (Object.keys(labels).length > 0) {
    service.labels = labels;
  }

  return service;
};

/* ------------------------------------------------------------------ */
/*  Models block emission                                             */
/* ------------------------------------------------------------------ */

const buildModelsBlock = (
  models: readonly Element[],
): Record<string, Record<string, string>> => {
  const out: Record<string, Record<string, string>> = {};
  for (const el of models) {
    // `description` для AI-model Element хранит image ref
    // (`ai/llama3.2` и т.п.) — loader пишет именно так, generator
    // эхо-эмитит.
    out[el.name] = { model: el.description || el.name };
  }
  return out;
};

/* ------------------------------------------------------------------ */
/*  Image inference (technology → image)                              */
/* ------------------------------------------------------------------ */

/**
 * Tech-string → docker image. Honour user-provided technology если
 * выглядит как image ref (`postgres:13`, `ghcr.io/org/repo:v1`,
 * `node`). Иначе для DB / Queue kinds — sensible default; для
 * generic Container — `undefined` (omitted в output: dev-команда
 * допишет руками; Compose Spec разрешает service без `image:`
 * когда есть `build:`).
 */
const inferImage = (el: Element): string | undefined => {
  const tech = el.technology?.trim();
  if (tech && tech.length > 0 && /^[\w./-]+(:[\w.-]+)?$/.test(tech)) {
    return tech.toLowerCase();
  }
  if (el.kind === "ContainerDb") return "postgres:latest";
  if (el.kind === "ContainerQueue") return "rabbitmq:latest";
  return undefined;
};

/* ------------------------------------------------------------------ */
/*  Relations → depends_on / models                                   */
/* ------------------------------------------------------------------ */

const collectDependsOn = (el: Element, model: Model): readonly string[] => {
  const targets: string[] = [];
  for (const rel of el.relations) {
    const target = model.elements[rel.to];
    if (!target) continue;
    if (target.external) continue;
    if (target.kind === "Person") continue;
    targets.push(rel.to);
  }
  return targets.toSorted((a, b) => a.localeCompare(b));
};

const collectAiModelRefs = (el: Element, model: Model): readonly string[] => {
  const refs: string[] = [];
  for (const rel of el.relations) {
    const target = model.elements[rel.to];
    if (target && isAiModelElement(target)) refs.push(rel.to);
  }
  return refs.toSorted((a, b) => a.localeCompare(b));
};

/* ------------------------------------------------------------------ */
/*  Labels — round-trip metadata                                      */
/* ------------------------------------------------------------------ */

const buildLabels = (el: Element, prefix: string): Record<string, string> => {
  const labels: Record<string, string> = {};
  // `aact.label` только когда отличается от auto-humanized name'а —
  // иначе loader восстановит через `humanize(name)` без подсказки.
  const canonicalLabel = humanize(el.name);
  if (el.label !== canonicalLabel) {
    labels[`${prefix}.label`] = el.label;
  }
  if (el.description.length > 0) {
    labels[`${prefix}.description`] = el.description;
  }
  if (el.tags.length > 0) {
    labels[`${prefix}.tags`] = el.tags.join(",");
  }
  if (el.link !== undefined && el.link.length > 0) {
    labels[`${prefix}.link`] = el.link;
  }
  if (shouldEmitKindLabel(el)) {
    labels[`${prefix}.kind`] = el.kind;
  }
  return labels;
};

/**
 * Эмитить `aact.kind` когда loader НЕ выведет правильный kind из
 * image-keyword. Component-family (ComponentDb / ComponentQueue / etc)
 * — всегда: image-heuristic выводит только Container-family. Для
 * Container-family проверяем что technology содержит kind-suggestive
 * keyword (postgres → ContainerDb, kafka → ContainerQueue), иначе
 * label обязателен для round-trip'а.
 */
const shouldEmitKindLabel = (el: Element): boolean => {
  if (el.kind === "Container") return false;
  if (el.kind.startsWith("Component")) return true;
  const tech = el.technology?.toLowerCase() ?? "";
  if (tech.length === 0) return true;
  if (
    el.kind === "ContainerDb" &&
    /postgres|mysql|mongo|redis|valkey/.test(tech)
  ) {
    return false;
  }
  if (el.kind === "ContainerQueue" && /kafka|rabbitmq|nats|pulsar/.test(tech)) {
    return false;
  }
  return true;
};

/* ------------------------------------------------------------------ */
/*  Humanize (mirrors loader's humanize)                              */
/* ------------------------------------------------------------------ */

const humanize = (raw: string): string =>
  raw
    .replaceAll(/[-_]+/g, " ")
    .replaceAll(/\b\w/g, (c) => c.toUpperCase())
    .trim();
